# Generated by Django 2.1.7 on 2019-03-12 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190312_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 16, 8, 38, 304381, tzinfo=utc)),
        ),
    ]
