# Generated by Django 2.1.7 on 2019-03-13 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190312_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 17, 49, 43, 122808, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
