# Generated by Django 2.1.7 on 2019-03-24 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190313_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 24, 9, 54, 20, 973948, tzinfo=utc)),
        ),
    ]
