# Generated by Django 2.1.7 on 2019-04-19 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190414_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isTemple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 12, 58, 12, 90351, tzinfo=utc)),
        ),
    ]
